name: build

on:
  push:
    branches:
      - main

jobs:
  build-src:
    runs-on: ubuntu-latest
    steps:
      - uses: rwu823/actions@main/packages/node-yarn-init
      - run: yarn build
      - run: du -sh out/*
      - name: Deploy to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: out
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
