name: build

on:
  push:
    branches:
      - main

jobs:
  src:
    steps:
      - uses: rwu823/bookmarklet/.github/workflows/workflow-build.yml@main
        with:
          file: src/www.voicetube.com.ts src/testing.ts
      - run: |
          du -sh out/**
