name: build

on:
  push:
    branches:
      - main

jobs:
  voicetube:
    uses: rwu823/bookmarklet/.github/workflows/workflow-build.yml@main
    with:
      file: src/www.voicetube.com.ts

  others:
    uses: rwu823/bookmarklet/.github/workflows/workflow-build.yml@main
    with:
      file: src/testing.ts

  publish:
    needs: [voicetube, others]
    runs-on: ubuntu-latest
    steps:
      - run: du -sh out/**
