name: build
on:
  push:
    branches:
      - main
jobs:
  esbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install --production
      - run: yarn build src/www.voicetube.com.ts
