name: build workflow

on:
  workflow_call:
    inputs:
      files:
        description: building file path.
        default: ''
        required: true
        type: string

jobs:
  esbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache-dependency-path: yarn.lock
      - run: yarn install
      - run: yarn build ${{ inputs.files }}
      - run: |
          cd out
          git init
          git add .
          git commit -m update
          git push -f origin HEAD:gh-pages
